export const SET_ORIGIN_ADDRESS = "SET_ORIGIN_ADDRESS";
export const SET_ORIGIN_GEOCODE = "SET_ORIGIN_GEOCODE";
export const SET_FREE_KEYWORD = "SET_FREE_KEYWORD";
export const SET_FREE_KEYWORDS = "SET_FREE_KEYWORDS";
export const SET_PLACES = "SET_PLACES";
export const CLEAR_PLACES = "CLEAR_PLACES";
export const SET_LOADING = "SET_LOADING";
