export const SET_ORIGIN_ADDRESS = "SET_ORIGIN_ADDRESS";
export const SET_ORIGIN_GEOCODE = "SET_ORIGIN_GEOCODE";
export const SET_PLACES = "SEARCH_PLACES";
export const CLEAR_PLACES = "CLEAR_PLACES";
export const SET_LOADING = "SET_LOADING";
